apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-eks-app
  template:
    metadata:
      labels:
        app: flask-eks-app
    spec:
      containers:
      - name: flask-container
        image: 970547333335.dkr.ecr.ap-south-1.amazonaws.com/flask-eks-app:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-eks-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
